#!/bin/bash

# Install apache
yum -y install httpd

# Set file and folder permissions
chgrp -R apache /home/ec2-user/
find /home/ec2-user/ -type d -exec chmod g+rx {} +
find /home/ec2-user/ -type f -exec chmod g+r {} +
chown -R ec2-user /home/ec2-user/
chown -R 775 /home/ec2-user/
find /home/ec2-user/ -type d -exec chmod u+rwx {} +
find /home/ec2-user/ -type f -exec chmod u+rw {} +

sed -i "s|AllowOverride None|AllowOverride All|g"  /etc/httpd/conf/httpd.conf
sed -i "s|/var/www/html|/var/www/html/public|g"  /etc/httpd/conf/httpd.conf
sed -i "s|index.html|index.php|g" /etc/httpd/conf/httpd.conf

yum -y install unzip
cd /var/www/html
wget https://github.com/Swa-ibu/Apr6/archive/refs/heads/main.zip
unzip main.zip
cd Apr6-main
mv ./* ../
cd /var/www/html
chown -R ec2-user:ec2-user /var/www/html
useradd -G ec2-user apache
chgrp -R apache storage bootstrap/cache
chmod -R ug+rwx storage bootstrap/cache
